modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/enhancednature/issues"

[[mods]]
modId="enhanced_nature"
version="1.1.0"
displayName="EnhancedNature"
itemIcon="minecraft:oak_sapling"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/Nature.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/enhancednature"
logoFile="logo.png"
#credits=""
authors="XxRexRaptorxX (RexRaptor)"
description='''
Enhances the nature of your world!
'''

[[dependencies.enhanced_nature]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enhanced_nature]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
