modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/enhancednature/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="minecraft:oak_sapling"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/EnhancedNature_NEO.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/enhancednature"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''Enhances the nature of your world!'''


[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

